name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
# renovate: datasource=github-releases depName=open-webui/open-webui
version: "0.6.41"
slug: "open-webui"
arch:
  - aarch64
  - amd64
url: https://openwebui.com
webui: 'http://[HOST]:[PORT:8080]/'  # The Web UI URL for the add-on
ingress: true  # Enable ingress to show the add-on inside Home Assistant UI
ingress_port: 8080
panel_icon: 'mdi:robot'  # Sidebar icon in Home Assistant
panel_title: "Open WebUI"  # Title shown in the Home Assistant sidebar
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
legacy: True
host_network: True
options:
  port: 8080
  env_vars: []
schema:
  port: port
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
init: false
startup: application
